Refactor: 인포윈도우 스타일링 방식 리펙토링
Hipspot/hipspot-web pull request #22
Opened 2023-01-24 08:21 UTC by hyorish03

## Motivation

<br>

## Key Changes

클래스네임으로 스타일링 된 부분을 스타일드 컴포넌트 형식으로 변경했습니다.

### 스크린샷

<br>

## To Reviewers

2023-01-24 09:26 UTC, sjsjsj1246 approved these changes
😍

2023-01-24 09:50 UTC, Sangjun-man commented on public/mockServiceWorker.js
> +  return new Response(response.body, response)
이거는 msw 기본제공 파일인거죠??
세미콜론만 없어진거 같은데 이거는 변경 내용 없애주시면 좋을것같아요~

2023-01-24 09:55 UTC, Sangjun-man commented on src/components/InfoWindow/index.tsx
> +        <Tab className="">인스타그램</Tab>
이부분 Styled Component랑 클래스네임이 같이 쓰여있어서 뭔지 살짝 헷갈릴것 같은데
props로 selected로 전달해주는게 어떨까요??

```suggestion
        <Tab isSelected={true}>업체제공사진</Tab>
        <Tab>메뉴</Tab>
        <Tab>인스타그램</Tab>
```
이렇게 해주고, 실제 styled-component에서는 props로 받아와서 스타일 설정 해주면 좋을것같아요~

2023-01-24 09:59 UTC, Sangjun-man commented on src/components/InfoWindow/Contents/Tab.tsx
> +  color: #999999;
앞에 컴포넌트에서 props로 isSelected 전달해줬다면

```suggestion
  color: ${(props) => props.isSelected ? "black": "gray" };
  filter : ${(props) => props.isSelected ? "none" :  "(brightness(0.99)" };
```
혹은
```suggestion
  ${(props) => props. isSelected ? `${selectedStyle}`: `${defaultStyle}` }
```
이런식으로 쓸수 있을것같아요~

2023-01-24 10:01 UTC, Sangjun-man commented on src/lib/states/infoWindowState.ts
> +// const initImageList: ImageCompProps[] = [
요 주석 친구들은 없애주셔도 좋을것같습니다~~

2023-01-24 10:03 UTC, Sangjun-man commented on src/components/InfoWindow/index.tsx
> +          <div className="left">
혹시 이 left class는 어디있을까요???

2023-01-24 10:04 UTC, Sangjun-man requested changes
아아주 좋습니다 고생 많으셨습니다~~ 리뷰 몇개 단거 피드백 해주시면 좋을것같습니다~~

2023-01-24 10:09 UTC, hyorish03 commented on src/components/InfoWindow/index.tsx
> +          <div className="left">
left에는 따로 CSS를 적용하지 않았지만 div 구분을 위해 className으로만 지정해뒀습니당. 따로 스타일링이 들어가있지 않으니 className 설정한 것을 그냥 지우는게 나을까요?!

2023-01-24 10:09 UTC, hyorish03 commented on src/lib/states/infoWindowState.ts
> +// const initImageList: ImageCompProps[] = [
넵넵!

2023-01-24 10:10 UTC, sjsjsj1246 commented on src/components/InfoWindow/index.tsx
> +        <Tab className="">인스타그램</Tab>
```suggestion
        <Tab isSelected>업체제공사진</Tab>
        <Tab>메뉴</Tab>
        <Tab>인스타그램</Tab>
```

이것도 좋아보여요

2023-01-25 12:36 UTC, yeoularu approved these changes
확인 완료했습니다 수고하셨습니다!!

2023-01-26 03:54 UTC, Sangjun-man commented on src/components/InfoWindow/index.tsx
> +        <Tab className="">인스타그램</Tab>
이게맞네요

2023-01-26 03:55 UTC, Sangjun-man commented on src/components/InfoWindow/index.tsx
> +          <div className="left">
음 제 의견은 아무 스타일링 없는 Styled component라도 만들어서 임포트 하는게 컴포넌트상 통일성 있어보이고 좋을것 같습니다. 나중에 스타일이 추가되면 거기에 바로 스타일 넣어도 되구요~

2023-01-26 04:49 UTC, sjsjsj1246 commented
@Sangjun-man 중복 제거하고 styled 수정했는데 확인 부탁드립니다.

2023-01-26 06:13 UTC, Sangjun-man reviewed
넵넵 확인했습니다 고생많으셨습니다~~~

2023-01-26 06:13 UTC, Sangjun-man approved these changes

2023-01-26 06:13 UTC, merged